plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nexa.iptv'
    compileSdk 36

    defaultConfig {
        applicationId 'com.nexa.iptv'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    def media3_version = '1.11.1'
    implementation "androidx.media3:media3-exoplayer:${media3_version}"
    implementation "androidx.media3:media3-exoplayer-hls:${media3_version}"
    implementation "androidx.media3:media3-exoplayer-dash:${media3_version}"
    implementation "androidx.media3:media3-ui:${media3_version}"
}
