import express from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import dns from 'dns/promises';
import net from 'net';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = process.env.PORT || 10000;
const JWT_SECRET = process.env.JWT_SECRET || 'nexa-editor-beta-' + crypto.createHash('sha256').update(process.env.RENDER_SERVICE_ID || 'local').digest('hex');
const DATA_DIR = path.join(__dirname,'data');
const DATA_FILE = path.join(DATA_DIR,'store.json');
fs.mkdirSync(DATA_DIR,{recursive:true});

let store={users:[],playlists:[],channels:[],seq:{user:1,playlist:1,channel:1}};
try{if(fs.existsSync(DATA_FILE))store=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch(e){console.error('Could not read store',e)}
function persist(){const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(store));fs.renameSync(tmp,DATA_FILE)}
function next(kind){const n=store.seq[kind]||1;store.seq[kind]=n+1;return n}
function now(){return new Date().toISOString()}

app.use(express.json({limit:'30mb'}));
app.use(express.static(path.join(__dirname,'public'),{etag:true,maxAge:'5m'}));
function clean(s,max=5000){return String(s??'').trim().slice(0,max)}
function tokenFor(user){return jwt.sign({uid:user.id,email:user.email},JWT_SECRET,{expiresIn:'14d'})}
function auth(req,res,next){const raw=req.headers.authorization||'';try{req.user=jwt.verify(raw.startsWith('Bearer ')?raw.slice(7):'',JWT_SECRET);next()}catch{res.status(401).json({error:'Unauthorized'})}}
function randomToken(){return crypto.randomBytes(18).toString('hex')}
function validHttpUrl(v){try{return ['http:','https:'].includes(new URL(v).protocol)}catch{return false}}
function isPrivateIp(ip){if(!ip)return true;if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||p[0]>=224}const x=ip.toLowerCase();return x==='::1'||x==='::'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe80:')}
async function assertSafeRemote(url){const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error('Only HTTP/HTTPS URLs are supported');if(u.hostname==='localhost'||u.hostname.endsWith('.local'))throw new Error('Local URLs are not allowed');const a=await dns.lookup(u.hostname,{all:true});if(!a.length||a.some(x=>isPrivateIp(x.address)))throw new Error('Private/local hosts are not allowed')}
async function fetchText(url){await assertSafeRemote(url);const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),20000);try{const r=await fetch(url,{signal:ctrl.signal,redirect:'follow',headers:{'User-Agent':'NEXA-IPTV-Editor/1.0','Accept':'application/x-mpegURL,text/plain,*/*'}});if(!r.ok)throw new Error(`Source returned HTTP ${r.status}`);const len=Number(r.headers.get('content-length')||0);if(len>25*1024*1024)throw new Error('Playlist is larger than 25 MB');const t=await r.text();if(t.length>25*1024*1024)throw new Error('Playlist is larger than 25 MB');return t}finally{clearTimeout(timer)}}
function parseAttrs(line){const out={};const re=/([\w-]+)="([^"]*)"/g;let m;while((m=re.exec(line)))out[m[1].toLowerCase()]=m[2];return out}
function parseM3u(text){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/);const channels=[];let meta=null,ua='',ref='';for(const raw of lines){const line=raw.trim();if(!line)continue;if(line.startsWith('#EXTINF')){const attrs=parseAttrs(line);const comma=line.indexOf(',');meta={attrs,name:comma>=0?line.slice(comma+1).trim():attrs['tvg-name']||'Unnamed channel'};ua='';ref=''}else if(/^#EXTVLCOPT:http-user-agent=/i.test(line))ua=line.split('=').slice(1).join('=').trim();else if(/^#EXTVLCOPT:http-referrer=/i.test(line)||/^#EXTVLCOPT:http-referer=/i.test(line))ref=line.split('=').slice(1).join('=').trim();else if(meta&&!line.startsWith('#')){const a=meta.attrs;channels.push({name:clean(meta.name,500),url:clean(line,5000),group_title:clean(a['group-title']||'Other',500),tvg_id:clean(a['tvg-id'],500),tvg_name:clean(a['tvg-name'],500),logo:clean(a['tvg-logo'],5000),user_agent:clean(ua,1000),referrer:clean(ref,5000),enabled:true});meta=null}}return channels.filter(c=>validHttpUrl(c.url))}
function escAttr(v=''){return String(v).replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/[\r\n]/g,' ')}
function m3uFor(p,channels){let out='#EXTM3U'+(p.epg_url?` x-tvg-url="${escAttr(p.epg_url)}"`:'')+'\n';for(const c of channels){const attrs=[c.tvg_id?`tvg-id="${escAttr(c.tvg_id)}"`:'',c.tvg_name?`tvg-name="${escAttr(c.tvg_name)}"`:'',c.logo?`tvg-logo="${escAttr(c.logo)}"`:'',c.group_title?`group-title="${escAttr(c.group_title)}"`:''].filter(Boolean).join(' ');out+=`#EXTINF:-1 ${attrs},${String(c.name||'Unnamed').replace(/[\r\n]/g,' ')}\n`;if(c.user_agent)out+=`#EXTVLCOPT:http-user-agent=${c.user_agent.replace(/[\r\n]/g,' ')}\n`;if(c.referrer)out+=`#EXTVLCOPT:http-referrer=${c.referrer.replace(/[\r\n]/g,' ')}\n`;out+=c.url+'\n'}return out}
function ownPlaylist(id,uid){return store.playlists.find(p=>String(p.id)===String(id)&&String(p.user_id)===String(uid))}
function playlistSummary(p){const cs=store.channels.filter(c=>String(c.playlist_id)===String(p.id));return {...p,channel_count:cs.length,enabled_count:cs.filter(c=>c.enabled).length,group_count:new Set(cs.map(c=>c.group_title||'Other')).size}}

app.post('/api/auth/register',async(req,res)=>{const email=clean(req.body.email,320).toLowerCase(),password=String(req.body.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return res.status(400).json({error:'Use a valid email and at least 8 characters for the password.'});if(store.users.some(u=>u.email===email))return res.status(409).json({error:'An account with this email already exists.'});const u={id:next('user'),email,password_hash:await bcrypt.hash(password,12),created_at:now()};store.users.push(u);persist();res.json({token:tokenFor(u),user:{id:u.id,email:u.email}})});
app.post('/api/auth/login',async(req,res)=>{const email=clean(req.body.email,320).toLowerCase(),password=String(req.body.password||''),u=store.users.find(x=>x.email===email);if(!u||!await bcrypt.compare(password,u.password_hash))return res.status(401).json({error:'Wrong email or password.'});res.json({token:tokenFor(u),user:{id:u.id,email:u.email}})});
app.get('/api/me',auth,(req,res)=>{const u=store.users.find(x=>String(x.id)===String(req.user.uid));if(!u)return res.status(401).json({error:'Account not found'});res.json({id:u.id,email:u.email,created_at:u.created_at})});

app.get('/api/playlists',auth,(req,res)=>res.json(store.playlists.filter(p=>String(p.user_id)===String(req.user.uid)).map(playlistSummary).sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at)))));
app.post('/api/playlists',auth,async(req,res)=>{const name=clean(req.body.name,200)||'My playlist',source=clean(req.body.sourceUrl,5000),epg=clean(req.body.epgUrl,5000);let text=String(req.body.m3uText||'');if(!text&&source)text=await fetchText(source);if(!text)return res.status(400).json({error:'Paste M3U content or provide a source URL.'});const parsed=parseM3u(text);if(!parsed.length)return res.status(400).json({error:'No HTTP/HTTPS channels were found in this playlist.'});const p={id:next('playlist'),user_id:req.user.uid,name,source_url:source,epg_url:epg,public_token:randomToken(),created_at:now(),updated_at:now()};store.playlists.push(p);let order=0;for(const c of parsed)store.channels.push({id:next('channel'),playlist_id:p.id,...c,sort_order:order++,created_at:now(),updated_at:now()});persist();res.json({...p,channel_count:parsed.length})});
app.get('/api/playlists/:id',auth,(req,res)=>{const p=ownPlaylist(req.params.id,req.user.uid);if(!p)return res.status(404).json({error:'Playlist not found'});const channels=store.channels.filter(c=>String(c.playlist_id)===String(p.id)).sort((a,b)=>a.sort_order-b.sort_order||a.id-b.id);res.json({playlist:p,channels})});
app.patch('/api/playlists/:id',auth,(req,res)=>{const p=ownPlaylist(req.params.id,req.user.uid);if(!p)return res.status(404).json({error:'Playlist not found'});if(clean(req.body.name,200))p.name=clean(req.body.name,200);p.epg_url=clean(req.body.epgUrl,5000);p.source_url=clean(req.body.sourceUrl,5000);p.updated_at=now();persist();res.json(p)});
app.delete('/api/playlists/:id',auth,(req,res)=>{const p=ownPlaylist(req.params.id,req.user.uid);if(!p)return res.status(404).json({error:'Playlist not found'});store.playlists=store.playlists.filter(x=>x!==p);store.channels=store.channels.filter(c=>String(c.playlist_id)!==String(p.id));persist();res.json({ok:true})});
app.post('/api/playlists/:id/refresh',auth,async(req,res)=>{const p=ownPlaylist(req.params.id,req.user.uid);if(!p)return res.status(404).json({error:'Playlist not found'});if(!p.source_url)return res.status(400).json({error:'This playlist has no source URL.'});const fresh=parseM3u(await fetchText(p.source_url)),old=store.channels.filter(c=>String(c.playlist_id)===String(p.id)),map=new Map(old.map(c=>[c.url,c]));store.channels=store.channels.filter(c=>String(c.playlist_id)!==String(p.id));let order=0;for(const c of fresh){const o=map.get(c.url);store.channels.push({id:next('channel'),playlist_id:p.id,name:o?.name||c.name,url:c.url,group_title:o?.group_title||c.group_title,tvg_id:o?.tvg_id||c.tvg_id,tvg_name:o?.tvg_name||c.tvg_name,logo:o?.logo||c.logo,user_agent:o?.user_agent||c.user_agent,referrer:o?.referrer||c.referrer,enabled:o?.enabled??true,sort_order:order++,created_at:now(),updated_at:now()})}p.updated_at=now();persist();res.json({ok:true,count:fresh.length})});

app.post('/api/playlists/:id/channels',auth,(req,res)=>{const p=ownPlaylist(req.params.id,req.user.uid);if(!p)return res.status(404).json({error:'Playlist not found'});const max=Math.max(-1,...store.channels.filter(c=>String(c.playlist_id)===String(p.id)).map(c=>c.sort_order));const c={id:next('channel'),playlist_id:p.id,name:clean(req.body.name,500)||'Unnamed channel',url:clean(req.body.url,5000),group_title:clean(req.body.groupTitle,500)||'Other',tvg_id:clean(req.body.tvgId,500),tvg_name:clean(req.body.tvgName,500),logo:clean(req.body.logo,5000),user_agent:clean(req.body.userAgent,1000),referrer:clean(req.body.referrer,5000),enabled:req.body.enabled!==false,sort_order:max+1,created_at:now(),updated_at:now()};if(!validHttpUrl(c.url))return res.status(400).json({error:'Use a valid HTTP/HTTPS stream URL.'});store.channels.push(c);p.updated_at=now();persist();res.json(c)});
app.patch('/api/channels/:id',auth,(req,res)=>{const c=store.channels.find(x=>String(x.id)===String(req.params.id)),p=c&&ownPlaylist(c.playlist_id,req.user.uid);if(!c||!p)return res.status(404).json({error:'Channel not found'});Object.assign(c,{name:clean(req.body.name,500)||'Unnamed channel',url:clean(req.body.url,5000),group_title:clean(req.body.groupTitle,500)||'Other',tvg_id:clean(req.body.tvgId,500),tvg_name:clean(req.body.tvgName,500),logo:clean(req.body.logo,5000),user_agent:clean(req.body.userAgent,1000),referrer:clean(req.body.referrer,5000),enabled:req.body.enabled!==false,updated_at:now()});if(!validHttpUrl(c.url))return res.status(400).json({error:'Use a valid HTTP/HTTPS stream URL.'});p.updated_at=now();persist();res.json(c)});
app.post('/api/channels/bulk',auth,(req,res)=>{const ids=new Set((Array.isArray(req.body.ids)?req.body.ids:[]).map(String));const allowed=new Set(store.playlists.filter(p=>String(p.user_id)===String(req.user.uid)).map(p=>String(p.id)));let count=0;if(req.body.action==='delete'){const before=store.channels.length;store.channels=store.channels.filter(c=>!(ids.has(String(c.id))&&allowed.has(String(c.playlist_id))));count=before-store.channels.length}else if(['enable','disable'].includes(req.body.action)){for(const c of store.channels)if(ids.has(String(c.id))&&allowed.has(String(c.playlist_id))){c.enabled=req.body.action==='enable';c.updated_at=now();count++}}else return res.status(400).json({error:'Unknown bulk action'});persist();res.json({ok:true,count})});
app.post('/api/playlists/:id/reorder',auth,(req,res)=>{const p=ownPlaylist(req.params.id,req.user.uid);if(!p)return res.status(404).json({error:'Playlist not found'});const pos=new Map((Array.isArray(req.body.ids)?req.body.ids:[]).map((id,i)=>[String(id),i]));for(const c of store.channels)if(String(c.playlist_id)===String(p.id)&&pos.has(String(c.id)))c.sort_order=pos.get(String(c.id));persist();res.json({ok:true})});
app.post('/api/playlists/:id/groups/rename',auth,(req,res)=>{const p=ownPlaylist(req.params.id,req.user.uid);if(!p)return res.status(404).json({error:'Playlist not found'});const from=clean(req.body.from,500),to=clean(req.body.to,500)||'Other';let count=0;for(const c of store.channels)if(String(c.playlist_id)===String(p.id)&&c.group_title===from){c.group_title=to;c.updated_at=now();count++}p.updated_at=now();persist();res.json({ok:true,count})});

app.get('/p/:token.m3u',(req,res)=>{const p=store.playlists.find(x=>x.public_token===req.params.token);if(!p)return res.status(404).send('Playlist not found');const channels=store.channels.filter(c=>String(c.playlist_id)===String(p.id)&&c.enabled).sort((a,b)=>a.sort_order-b.sort_order||a.id-b.id);res.set({'Content-Type':'application/x-mpegURL; charset=utf-8','Content-Disposition':`inline; filename="${p.name.replace(/[^a-z0-9_-]+/gi,'_')}.m3u"`,'Cache-Control':'no-store'}).send(m3uFor(p,channels))});
app.get('/p/:token.json',(req,res)=>{const p=store.playlists.find(x=>x.public_token===req.params.token);if(!p)return res.status(404).json({error:'Playlist not found'});res.json({playlist:{id:p.id,name:p.name,epg_url:p.epg_url},channels:store.channels.filter(c=>String(c.playlist_id)===String(p.id)&&c.enabled).sort((a,b)=>a.sort_order-b.sort_order||a.id-b.id).map(({name,url,group_title,tvg_id,tvg_name,logo,user_agent,referrer})=>({name,url,group_title,tvg_id,tvg_name,logo,user_agent,referrer}))})});
app.get('/health',(req,res)=>res.json({ok:true,playlists:store.playlists.length,channels:store.channels.length}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:err.name==='AbortError'?'Source request timed out.':(err.message||'Server error')})});
app.listen(PORT,()=>console.log(`NEXA IPTV Editor listening on ${PORT}`));
